In [1]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re

# TODO

For each draft class since 2000.
- Look for players that have 'strong' html tage around the name
 - This indicates that the player is currently an active NFL player, according to PFR
- Get the player ids of those players
- Then read in the player draft csv
- Then match the active ids to the ones in the draft csv
- Then Create a column indicating that the end of a player's careers has been observed (1 if it has been and 0 if it hasn't, this is how lifelines package likes it).

# Scrape all the active drafted player ids.

In [2]:
all_active_players = []

In [3]:
# according pfr the last player Sebstian Janikowski is the earlest
# active player drafted (2000 draft)
# NOTE undrafted players are not included in this, so guys like Adam Vinatieri
# are not included
for year in range(2000,2016):
    # get the html and extract the data based off the proper CSS selector
    url = "http://www.pro-football-reference.com/years/{}/draft.htm".format(year)
    html = urlopen(url)
    soup = BeautifulSoup(html, "lxml")
    # active drafted players are bolded in the draft table on pfr
    player_html = soup.select("#drafts strong a")
    # get the link for each
    player_links = [player["href"] for player in player_html]
    # add these links to the large list active player lists
    all_active_players.extend(player_links)

In [4]:
# Extract the player ids for each using regex
active_player_ids = [re.search(r"/.*/.*/(.*)\.", player).group(1) for player
                     in all_active_players]

In [5]:
active_player_ids[:5] # just check things out, need to drop charles woodson as he's retired

['janikseb01', 'LechSh20', 'BradTo00', 'VickMi00', 'BreeDr00']

# Read in draft csv and create an indicator for active players up till 2015 season.

- Drop all players drafted in the 2016 draft
- Then deal with censorship
    - Right censored data are players who are still active as we do not know their "full survival time."
    - That column will be labeled "Retired" with 1 indicating that it has been observed, and 0 if it hasn't.
    - Players that are considered active have their player id in the `active_player_ids` list.  
- Also will need to fix some players who are active but don't have an "Up To" value of 2015 due to injury.  This indicates an injury that kept them from playing for the season (e.g. Kelvin Benjamin).

In [6]:
draft_df = pd.read_csv("data/pfr_nfl_draft_data_CLEAN.csv")

In [7]:
draft_df.head()

,Draft_Yr,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Rush_Yds,Rush_TD,Rec,Rec_Yds,Rec_TD,Tkl,Def_Int,Sk,College,Player_ID
0,1967,1,1,BAL,Bubba Smith,DE,22.0,1976.0,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Michigan St.,SmitBu00
1,1967,1,2,MIN,Clint Jones,RB,22.0,1973.0,0,0,...,2178.0,20.0,38.0,431.0,0.0,0.0,0.0,0.0,Michigan St.,JoneCl00
2,1967,1,3,SFO,Steve Spurrier,QB,22.0,1976.0,0,0,...,258.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,Florida,SpurSt00
3,1967,1,4,MIA,Bob Griese,QB,22.0,1980.0,2,8,...,994.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,Purdue,GrieBo00
4,1967,1,5,HOU,George Webster,LB,21.0,1976.0,3,3,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,Michigan St.,WebsGe00

In [8]:
# keep only players before the 2016 draft
draft_df = draft_df.loc[draft_df.Draft_Yr < 2016]

In [9]:
draft_df.tail()

,Draft_Yr,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Rush_Yds,Rush_TD,Rec,Rec_Yds,Rec_TD,Tkl,Def_Int,Sk,College,Player_ID
15587,2015,7,252,DEN,Josh Furman,DB,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Oklahoma St.,FurmJo00
15588,2015,7,253,NWE,Xzavier Dickson,OLB,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Alabama,DickXz00
15589,2015,7,254,SFO,Rory 'Busta' Anderson,TE,22.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,South Carolina,AndeRo02
15590,2015,7,255,IND,Denzell Goode,T,24.0,2015.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Mars Hill,GoodDe01
15591,2015,7,256,ARI,Gerald Christian,TE,24.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Louisville,ChriGe00

## To check if a player is active, check if their player id is in the `active_players_ids` list using the `isin` method.

In [10]:
# the most recent players should be considered active, as they are still
# on the roster
draft_df.Player_ID.isin(active_player_ids)[-10:]

15582    True
15583    True
15584    True
15585    True
15586    True
15587    True
15588    True
15589    True
15590    True
15591    True
Name: Player_ID, dtype: bool

In [11]:
# create a seriess indicating whether a player is active
active = draft_df.Player_ID.isin(active_player_ids)

# Now create a column indicating that a player's career is officially over
# via ~ and convert it to 1s and 0s
draft_df["Retired"] = (~active).astype(int)

In [12]:
draft_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15592 entries, 0 to 15591
Data columns (total 31 columns):
Draft_Yr     15592 non-null int64
Rnd          15592 non-null int64
Pick         15592 non-null int64
Tm           15592 non-null object
Player       15592 non-null object
Pos          15592 non-null object
Age          15592 non-null float64
To           15592 non-null float64
AP1          15592 non-null int64
PB           15592 non-null int64
St           15592 non-null int64
CarAV        15592 non-null float64
DrAV         15592 non-null float64
G            15592 non-null float64
Cmp          15592 non-null float64
Att          15592 non-null float64
Yds          15592 non-null float64
TD           15592 non-null float64
Int          15592 non-null float64
Rush_Att     15592 non-null float64
Rush_Yds     15592 non-null float64
Rush_TD      15592 non-null float64
Rec          15592 non-null float64
Rec_Yds      15592 non-null float64
Rec_TD       15592 non-null float64
Tkl          15592 non-null float64
Def_Int      15592 non-null float64
Sk           15592 non-null float64
College      15534 non-null object
Player_ID    11163 non-null object
Retired      15592 non-null int64
dtypes: float64(19), int64(7), object(5)
memory usage: 3.8+ MB

## Check the players labeled as active

Note that there are different years for the  "To" column even tho pfr labels them as active players.  For example the 0's represent some players who were drafted in the 2015 draft but didn't play (e.g. Kevin White).  There are players with "To" values that are less than 2015 even though they are considered active players by PFR.  For example Jordy Nelson has a to value of 2014, due to the fact that he was hurt for the 2015 regular season because of his ACL injury.  Then there are journeymen who constantly get signed and cut there but never get playing time so they don't register any information for a given season.  

For this analysis any player who is considered active by PFR, I will consider consider as active players regardless of whether they played a game for the 2015 season.  They will be considered right-censored data points as we do not know when they will be out of the league for good.

In [13]:
draft_df.loc[draft_df.Retired == 0, "To"].value_counts()

2015.0    1327
2014.0     153
0.0         93
2013.0      45
2012.0      10
2011.0       2
Name: To, dtype: int64

In [14]:
draft_df.loc[(draft_df.Retired == 0) & (draft_df.To == 2014),
             ["Player", "Player_ID"]]

                      Player Player_ID
12124          Dave Zastudil  ZastDa20
13006        Kevin Vickerson  VickKe99
13185         Parys Haralson  HaraPa20
13239       Bruce Gradkowski  GradBr00
13326        Anthony Spencer  SpenAn99
13455          Dante Rosario  RosaDa00
13461           Will Herring  HerrWi99
13482           Adam Hayward  HaywAd98
13492         Desmond Bishop  BishDe99
13567             Ryan Clady  CladRy20
13591           Jordy Nelson  NelsJo00
13607         Quentin Groves  GrovQu99
13612             Chad Henne  HennCh01
13698      Orlando Scandrick  ScanOr99
13729            Josh Morgan  MorgJo00
13731          Jalen Parmele  ParmJa00
13742          John Sullivan  SullJo24
13749             Ryan Mundy  MundRy00
13764             Matt Flynn  FlynMa00
13823          Larry English  EnglLa99
13840           Louis Delmas  DelmLo99
13850         Everette Brown  BrowEv99
13861          Phil Loadholt  LoadPh20
13867            Will Beatty  BeatWi20
13876         Jason Williams  WillJa95
13878       Matt Shaughnessy  ShauMa99
13917          Victor Butler  ButlVi99
13989            Jarius Wynn  WynnJa99
14001         Brandon Gibson  GibsBr00
14020           Paul Fanaika  FanaPa20
...                      ...       ...
15014             Mike James  JameMi00
15022          Cobi Hamilton  HamiCo00
15023            Chris Jones  JoneCh04
15027          Khalid Wooten  WootKh00
15051       Michael Buchanan  BuchMi00
15052         Garrett Gilkey  GilkGa00
15056              Ty Powell  PoweTy00
15060      Steve Beauharnais  BeauSt00
15107        Kelvin Benjamin  BenjKe00
15128             Jace Amaro  AmarJa00
15137  Stanley Jean-Baptiste  JeanSt00
15183         Jalen Saunders  SaunJa00
15199           Logan Thomas  ThomLo00
15205           Khairi Fortt  FortKh00
15214             Tom Savage  SavaTo00
15231              Nat Berhe  BerhNa00
15232       Cyril Richardson  RichCy00
15246         Vinnie Sunseri  SunsVi00
15248          Ronald Powell  PoweRo01
15264          Robert Herron  HerrRo00
15267            E.J. Gaines  GainE.00
15274          Brandon Dixon  DixoBr00
15280           Marion Grice  GricMa00
15285           Jemea Thomas  ThomJe03
15291        Marquis Flowers  FlowMa00
15301          Storm Johnson  JohnSt03
15304           Jabari Price  PricJa00
15306            Kiero Small  SmalKi00
15318           James Wright  WrigJa03
15326       Jonathan Dowling  DowlJo00

[153 rows x 2 columns]

In [15]:
# https://stackoverflow.com/questions/27163830/ipython-notebook-pandas-max-allowable-columns
from IPython.display import display

with pd.option_context("display.max_rows", None):
    display(draft_df.loc[(draft_df.Retired == 0) & (draft_df.To == 2013), 
                         ["Player", "Player_ID"]])

                   Player Player_ID
12599     Darnell Dockett  DockDa20
13320          Aaron Ross  RossAa99
13452     Antonio Johnson  JohnAn03
13618      Terrell Thomas  ThomTe99
13715        Josh Johnson  JohnJo05
13750       Donald Thomas  ThomDo26
13863          Fili Moala  MoalFi99
13920       Vaughn Martin  MartVa99
14110    Daryl Washington  WashDa99
14171         Jacoby Ford  FordJa01
14269       Kyle Williams  WillKy01
14290     Dorin Dickerson  DickDo00
14393        John Moffitt  MoffJo00
14399   DeMarcus Van Dyke  VanDDe00
14408        Curtis Marsh  MarsCu01
14413        Curtis Brown  BrowCu01
14429         Clyde Gates  GateCl00
14441         Tandon Doss  DossTa00
14459       D.J. Williams  WillD.00
14485         Ryan Whalen  WhalRy00
14495        Evan Royster  RoysEv00
14502        David Carter  CartDa01
14571         Chris Neild  NeilCh00
14577     Justin Blackmon  BlacJu00
14615        Stephen Hill  HillSt00
14650       Michael Egnew  EgneMi00
14662       Jake Bequette  BequJa00
14679         Devon Wylie  WyliDe00
14688       Orson Charles  CharOr00
14720     Chris Greenwood  GreeCh01
14740        Juron Criner  CrinJu00
14742        Vick Ballard  BallVi00
14750          Mark Asper  AspeMa00
14768         Jonte Green  GreeJo03
14772  Brandon Washington  WashBr00
14788       D.J. Campbell  CampD.00
14800     Jeris Pendleton  PendJe00
14812       David Paulson  PaulDa01
14819        Brad Smelley  SmelBr00
14824    Daryl Richardson  RichDa00
14948        Chris Harper  HarpCh00
14959    Sanders Commings  CommSa00
14997           Nick Kasa  KasaNi00
15039         Travis Bond  BondTr00
15067       Michael Bowie  BowiMi00

In [16]:
draft_df.loc[(draft_df.Retired == 0) & (draft_df.To == 2012), 
             ["Player", "Player_ID"]]

                 Player Player_ID
12295      Rex Grossman  GrosRe00
13898       Deon Butler  ButlDe00
13940     Tyronne Green  GreeTy20
14088         Tim Tebow  TeboTi00
14102    Arrelious Benn  BennAr00
14453      Ricky Stanzi  StanRi00
14486     Demarcus Love  LoveDe00
14732       Ryan Miller  MillRy00
14785  Richard Crawford  CrawRi00
14806      Marcel Jones  JoneMa03

In [17]:
draft_df.loc[(draft_df.Retired == 0) & (draft_df.To == 2011), 
             ["Player", "Player_ID"]]

                 Player Player_ID
14185        Mike Kafka  KafkMi00
14240  Carlton Mitchell  MitcCa00

In [18]:
draft_df.loc[(draft_df.Retired == 0) & (draft_df.To == 0), 
             ["Player", "Player_ID", "Draft_Yr"]]

                      Player Player_ID  Draft_Yr
14920         Sam Montgomery  MontSa00      2013
14962         Jesse Williams  WillJe02      2013
15001     David Quessenberry  QuesDa00      2013
15003       William Campbell  CampWi00      2013
15020            Alan Bonner  BonnAl00      2013
15037             Joe Kruger  KrugJo00      2013
15046          Brad Sorensen  SoreBr00      2013
15050            Eric Herman  HermEr00      2013
15059             Zac Dysert  DyseZa00      2013
15066            Jared Smith  SmitJa02      2013
15071        Carter Bykowski  BykoCa00      2013
15072           Marc Anthony  AnthMa00      2013
15179         Brandon Thomas  ThomBr02      2014
15194        Shaquelle Evans  EvanSh00      2014
15200          Carl Bradford  BradCa01      2014
15215          Larry Webster  WebsLa00      2014
15222         Kadeem Edwards  EdwaKa00      2014
15224           David Yankey  YankDa00      2014
15234           Arthur Lynch  LyncAr00      2014
15236   Shaquille Richardson  RichSh01      2014
15242           Aaron Murray  MurrAa00      2014
15247        Marquis Spruill  SpruMa00      2014
15251           Jimmy Staten  StatJi00      2014
15258            Jon Halapio  HalaJo00      2014
15262            David Fales  FaleDa00      2014
15263          Kendall James  JameKe00      2014
15265        Lache Seastrunk  SeasLa00      2014
15266        Bennett Jackson  JackBe00      2014
15271         Jordan Zumwalt  ZumwJo00      2014
15273          Keith Wenning  WennKe00      2014
...                      ...       ...       ...
15511           Robert Myers  MyerRo01      2015
15513          Matthew Wells  WellMa00      2015
15514             Max Valles  VallMa00      2015
15517          Tevin Mitchel  MitcTe01      2015
15520         Tyrus Thompson  ThomTy01      2015
15526       JaCorey Shepherd  ShepJa00      2015
15528            B.J. Dubose  DuboB.00      2015
15533         Randall Telfer  TelfRa00      2015
15537             A.J. Derby  DerbA.00      2015
15545        Christian Ringo  RingCh00      2015
15546         Reshard Cliett  ClieRe00      2015
15553         Anthony Morris  MorrAn00      2015
15556           Andre Debose  DeboAn00      2015
15557          Austin Reiter  ReitAu00      2015
15558             Deon Simon  SimoDe00      2015
15562           Martin Ifedi  IfedMa00      2015
15564             Ben Koyack  KoyaBe00      2015
15568           Da'Ron Brown  BrowDa03      2015
15570         Kenny Hilliard  HillKe01      2015
15572          Brian Mihalik  MihaBr00      2015
15574         Gerod Holliman  HollGe00      2015
15576        Ifo Ekpre-Olomu  EkprIf00      2015
15578        Laurence Gibson  GibsLa00      2015
15582         Darryl Roberts  RobeDa00      2015
15583            Ryan Murphy  MurpRy00      2015
15586          Taurean Nixon  NixoTa00      2015
15587            Josh Furman  FurmJo00      2015
15588        Xzavier Dickson  DickXz00      2015
15589  Rory 'Busta' Anderson  AndeRo02      2015
15591       Gerald Christian  ChriGe00      2015

[93 rows x 3 columns]

In [19]:
# Mike Kafka is retired according to wikipedia, but PFR still has him
# as an active player. so set him as retired
# NOTE other players may have this issue, but I'm too lazy to deal with it...
draft_df.loc[draft_df.Player == "Mike Kafka", "Retired"] = 1

## Calculate career duration.

Career duration will just be the difference between "Draft_Yr" and "To", plus one. So players who were drafted in 2015 and played in 2015 will have played for 1 year.  For players who have a 0 value for "To" then they, they will have a value of 0 for their duration.

In [20]:
# https://stackoverflow.com/questions/26886653/pandas-create-new-column-based-on-values-from-other-columns

# function calculate the career duration for each player
def calc_duration(player):
    """
    Calculte the years played for a player. If the 'To' value is 0 then return
    the value 0.  Otherwise set that column value to equal 
    'To' - 'Draft_Yr' + 1.
    """
    
    # The player never played a season if their "To" value is 0, so return 0
    if player["To"] == 0:
        return 0
    
    # Otherwise return the number of years they played.
    duration = player["To"] - player["Draft_Yr"] + 1
    return duration

In [23]:
# Now create a Duration column, by applying the above function to each
# row, which represents a player
# to apply the function to each row, you must use axis=1
draft_df["Duration"]  = draft_df.apply(lambda player: calc_duration(player),
                                           axis=1)

In [24]:
draft_df.head()

,Draft_Yr,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Rec,Rec_Yds,Rec_TD,Tkl,Def_Int,Sk,College,Player_ID,Retired,Duration
0,1967,1,1,BAL,Bubba Smith,DE,22.0,1976.0,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,Michigan St.,SmitBu00,1,10.0
1,1967,1,2,MIN,Clint Jones,RB,22.0,1973.0,0,0,...,38.0,431.0,0.0,0.0,0.0,0.0,Michigan St.,JoneCl00,1,7.0
2,1967,1,3,SFO,Steve Spurrier,QB,22.0,1976.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,Florida,SpurSt00,1,10.0
3,1967,1,4,MIA,Bob Griese,QB,22.0,1980.0,2,8,...,0.0,0.0,0.0,0.0,0.0,0.0,Purdue,GrieBo00,1,14.0
4,1967,1,5,HOU,George Webster,LB,21.0,1976.0,3,3,...,0.0,0.0,0.0,0.0,5.0,0.0,Michigan St.,WebsGe00,1,10.0

In [25]:
draft_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15592 entries, 0 to 15591
Data columns (total 32 columns):
Draft_Yr     15592 non-null int64
Rnd          15592 non-null int64
Pick         15592 non-null int64
Tm           15592 non-null object
Player       15592 non-null object
Pos          15592 non-null object
Age          15592 non-null float64
To           15592 non-null float64
AP1          15592 non-null int64
PB           15592 non-null int64
St           15592 non-null int64
CarAV        15592 non-null float64
DrAV         15592 non-null float64
G            15592 non-null float64
Cmp          15592 non-null float64
Att          15592 non-null float64
Yds          15592 non-null float64
TD           15592 non-null float64
Int          15592 non-null float64
Rush_Att     15592 non-null float64
Rush_Yds     15592 non-null float64
Rush_TD      15592 non-null float64
Rec          15592 non-null float64
Rec_Yds      15592 non-null float64
Rec_TD       15592 non-null float64
Tkl          15592 non-null float64
Def_Int      15592 non-null float64
Sk           15592 non-null float64
College      15534 non-null object
Player_ID    11163 non-null object
Retired      15592 non-null int64
Duration     15592 non-null float64
dtypes: float64(20), int64(7), object(5)
memory usage: 3.9+ MB

In [26]:
draft_df.columns

Index(['Draft_Yr', 'Rnd', 'Pick', 'Tm', 'Player', 'Pos', 'Age', 'To', 'AP1',
       'PB', 'St', 'CarAV', 'DrAV', 'G', 'Cmp', 'Att', 'Yds', 'TD', 'Int',
       'Rush_Att', 'Rush_Yds', 'Rush_TD', 'Rec', 'Rec_Yds', 'Rec_TD', 'Tkl',
       'Def_Int', 'Sk', 'College', 'Player_ID', 'Retired', 'Duration'],
      dtype='object')

In [27]:
# convert some colums from float to int
cols_to_int = ['Age', 'To', 'G', 'Cmp', 'Att', 'Yds', 'TD', 'Int',
               'Rush_Att', 'Rush_Yds', 'Rush_TD', 'Rec', 'Rec_Yds', 'Rec_TD', 
               'Def_Int', 'Duration']

In [28]:
draft_df.loc[:, cols_to_int] = draft_df.loc[:, cols_to_int].astype(int)

In [29]:
draft_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15592 entries, 0 to 15591
Data columns (total 32 columns):
Draft_Yr     15592 non-null int64
Rnd          15592 non-null int64
Pick         15592 non-null int64
Tm           15592 non-null object
Player       15592 non-null object
Pos          15592 non-null object
Age          15592 non-null int64
To           15592 non-null int64
AP1          15592 non-null int64
PB           15592 non-null int64
St           15592 non-null int64
CarAV        15592 non-null float64
DrAV         15592 non-null float64
G            15592 non-null int64
Cmp          15592 non-null int64
Att          15592 non-null int64
Yds          15592 non-null int64
TD           15592 non-null int64
Int          15592 non-null int64
Rush_Att     15592 non-null int64
Rush_Yds     15592 non-null int64
Rush_TD      15592 non-null int64
Rec          15592 non-null int64
Rec_Yds      15592 non-null int64
Rec_TD       15592 non-null int64
Tkl          15592 non-null float64
Def_Int      15592 non-null int64
Sk           15592 non-null float64
College      15534 non-null object
Player_ID    11163 non-null object
Retired      15592 non-null int64
Duration     15592 non-null int64
dtypes: float64(4), int64(23), object(5)
memory usage: 3.9+ MB

In [30]:
draft_df.to_csv("data/nfl_survival_analysis_data.csv", index=False)